
---
title: "Mapping"
author: "Gabriel Prunier-Duparge"
date: "3 décembre 2018"
output: html_document
---

```{r}
#install.packages("leaflet")
#install.packages("sp")
```

```{r, message = FALSE}
library(leaflet)
library(maps)
library(rgdal)
library(sp)
library(tidyverse)
library(readr)
```

```{r}

m <- leaflet() %>%
  addTiles() %>%
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
m 

```


```{r}
df = data.frame(Lat = 30:40, Long = rnorm(11))
leaflet(df) %>% addCircles() %>% addTiles()
```

```{r}

mapStates = map("france", fill = TRUE, plot = FALSE)
leaflet(data = mapStates) %>% addTiles() %>%
  addPolygons(fillColor = topo.colors(10, alpha = NULL), stroke = FALSE)

```


```{r}
#Tentative de mettre les shapes de département

departments_shp <- readOGR( dsn=getwd(),
  layer = "departements-20180101")

#head(departments_shp)
#summary(departments_shp)
View(departments_shp)

departments_shp@data
```


```{r}
leaflet(data = departments_shp) %>% 
  addTiles() %>% 
  setView(lat = 48.5, lng = 2.5, zoom = 5) %>% 
  addPolygons(fillColor = "blue", 
              highlight = highlightOptions(color = "red", bringToFront = TRUE), label=~nom)
```

```{r}
#Travail sur l'élimination de variables et compagnies

#Création d'une variable de travail
departements_test <- departments_shp
departements_test@data

# departements_test@data <- departements_test@data %>% 
#   filter(code_insee == "75")
# 
# leaflet(data = departements_test) %>% 
#   addTiles() %>% 
#   setView(lat = 48.5, lng = 2.5, zoom = 5) %>% 
#   addPolygons(fillColor = "blue", 
#               highlight = highlightOptions(color = "red", bringToFront = TRUE), label=~nom)

departements_test_sub <- departements_test[departements_test$code_insee == "87",]

leaflet(data = departements_test_sub) %>% 
  addTiles() %>%
  setView(lat = 48.5, lng = 2.5, zoom = 5) %>%
  addPolygons(fillColor = "blue",
              highlight = highlightOptions(color = "red", bringToFront = TRUE), label=~nom)

```

```{r}
#Let's get rid of overseas department

departements_test <- departements_test[!departements_test$code_insee %in%c("971", "972", "973", "974", "975", "976", "69M"),]
departements_test@data


leaflet(data = departements_test) %>% 
  addTiles() %>%
  setView(lat = 48.5, lng = 2.5, zoom = 5) %>%
  addPolygons(fillColor = "blue",
              highlight = highlightOptions(color = "red", bringToFront = TRUE), label=~nom)

```


```{r}
dep_light <- readOGR(dsn = "departements-20140306-100m-shp", layer = "departements-20140306-100m")

leaflet(data = dep_light) %>% 
  addTiles() %>% 
  setView(lat = 47.5, lng = 2.5, zoom = 6) %>% 
  addPolygons(fillColor = "green", highlight = highlightOptions(color = "red", bringToFront = TRUE), label = ~nom)

```

```{r}
dep_light <- dep_light[!dep_light$code_insee %in%c("971", "972", "973", "974", "976"),]
dep_light@data

```



```{r}
rail_72 <- readOGR(dsn = "departement-72", layer = "railways")
points_72 <- readOGR(dsn = "departement-72", layer = "points")

points_72_H <- points_72[points_72$type == "hospital",]

leaflet(data=points_72_H) %>% 
  addTiles() %>% 
  setView(lat=47.5, lng = 2.5, zoom = 8) %>% 
  addCircleMarkers(label = ~type)


points_72@data %>% 
  group_by(points_72$type) %>% 
  summarise(tot = n())
```





Ok on commence le boulot d'écrire des fonctions et de faire de la prédiction

```{r}
equipment <- read.csv("Data/equipment.csv")

```


```{r}
dim(equipment)
summary(equipment)
head(equipment)
View(equipment)
names(equipment)
```

```{r}
pauvrete <- read_excel("Data/niveau_vie_dep.xlsx")
summary(pauvrete)
```

```{r}
library(FactoMineR)
```

```{r}
niveau_vie <- pauvrete %>% 
  select(niveau_de_vie_median)
niveau_vie


df_travail <- equipment %>% 
  mutate(niv_vie = niveau_vie$niveau_de_vie_median)
df_travail

df_travail <- df_travail %>% 
  select(dep, Etablissement.sante.court.sejour, Etablissement.sante.moyen.sejour, Etablissement.sante.long.sejour)

```

```{r}
res.pca <- PCA(df_travail, scale.unit = TRUE, quali.sup = 1)
```

```{r}
library(stringr)
```


```{r}
dep_depense <- read_excel("Data/cgd_2017 (3).xlsx", 
    sheet = "T01")

dep_depense <- dep_depense[-c(1:5),]
dep_depense <- dep_depense[-c(97:106),]

dep_depense <- dep_depense[, c(1,2)]
names(dep_depense) <- c("departement", "depense")

dep_depense <- dep_depense %>% 
  mutate(code_insee = substring(departement, 1, 2)) %>% 
  mutate(nom = str_sub(departement, 4))

dep_depense <- dep_depense[, c(3, 4, 2)]

View(dep_depense)


```

```{r}
df_travail2 <- df_travail %>% 
  mutate(depense = as.numeric(dep_depense$depense))
df_travail2

res.pca <- PCA(df_travail2, scale.unit = TRUE, quali.sup = 2, quanti.sup = c(1, 3:19, 21, 23))

```


```{r}
#dep_education <- read.csv("Data/dep_education.csv")
```

```{r}
# categories_edu <- dep_edu %>%
#   distinct(nature_uai_libe)
# categories_edu
```



```{r}
# dep_edu <- read.csv("Data/dep_edu.csv")
# 
# df_edu <- equipment
# 
# 
# education_par_dep <- dep_edu %>% 
#   group_by(dpt) %>%
#   filter(nature_uai_libe == "Collège") %>% 
#   summarise(college = n())


```

```{r}
# lycee_pro <- dep_edu %>%
#   group_by(dpt) %>% 
#   filter(nature_uai_libe == "Lycée polyvalent") %>% 
#   summarise(colonne = n())
# 
#merge(lycee_pro, education_par_dep)
```

#Education 


```{r}
edudep <- read_excel("Data/TCRD_061.xlsx")
View(edudep)
```

```{r}
edudep <- edudep[c(5:100),]
edudep <- edudep[,-6]
```

```{r}

edudep <- edudep %>% 
  mutate(college = as.numeric(X__2)+as.numeric(X__6)) %>% 
  mutate(lycee_professionnel = as.numeric(X__3)+as.numeric(X__7)) %>% 
  mutate(lycee_general_techno = as.numeric(X__4)+ as.numeric(X__8)) %>% 
  mutate(total_edu = as.numeric(X__9))

edudep <- edudep[, -c(3:9)]

names(edudep) <- c("code_insee", "nom", "college", "lycee_professionnel", "lycee_general_techno", "total")

```


```{r}
write.csv(edudep, "education_per_department.csv")
```


#On écrit les fonctions

```{r}
tot <- equipment
indicateurs <- edudep


find_equipment = function(indic, eq = tot, ind = indicateurs){
  indic <- enquo(indic)
  new_dataset <- eq %>% dplyr::select(-c(1,2))
  col <- ind %>% 
    dplyr::select(column_name = !!indic)
  new_dataset <- add_column(new_dataset, indicator = col$column_name)
  return(new_dataset)
}

find_equipment(college)


```

#Création du df indicateurs et complétion du df equipment


```{r}
equipment
```

```{r}
demographics <- read_excel(path ="Data/base-ic-evol-struct-pop-2013.xlsx", sheet = 1, skip = 5)
View(demographics)

demographics_by_dep <- demographics %>% 
  group_by(DEP) %>% 
  select_if(is.numeric) %>% 
  summarise_all(funs(sum_pop = sum))

demographics_by_dep <- demographics_by_dep %>% 
  filter(DEP<=95) %>% 
  select(code_insee = DEP, population = P13_POP_sum_pop)

View(demographics_by_dep)
demographics_by_dep
```

```{r}
edudep

edu_par_hab <- merge(edudep, demographics_by_dep,by = "code_insee")
edu_par_hab

edu_par_hab <- edu_par_hab %>% 
  mutate(college = college/population) %>% 
  mutate(lycee_professionnel = lycee_professionnel/population) %>% 
  mutate(lycee_general_techno = lycee_general_techno/population) %>% 
  mutate(total_education = total/population)

edu_par_hab <- edu_par_hab %>%
  select(dep = code_insee, college, lycee_professionnel, lycee_general_techno, total_education)
  
```

```{r}
equipment <- merge(equipment, edu_par_hab, by = "dep")
equipment  

```

```{r}
equip_dep <- read.dbf(file = "Data/bpe1217_nbequip_dep.dbf")
equip_dep
```

```{r}
equip_loisir <- equip_dep %>% 
  filter(typequ %in% c("F101", "F102", "F103", "F104", "F107", "F108", "F109", "F110", "F117")) %>% 
  select(dep, typequ, nombre = "nb_2012")

equip_loisir


  
```

```{r}
eq_loisir <- merge(eq_loisir, equip_loisir %>% 
        filter(typequ == "F117")%>%
        select(dep, skate_park = nombre), 
      by = "dep")
eq_loisir

eq_loisir <- eq_loisir[-c(97:100),]

eq_loisir <- eq_loisir %>% 
  select(code_insee=dep, everything())

```

```{r}
eq_loisir_hab <- merge(eq_loisir, demographics_by_dep, by = "code_insee")

eq_loisir_hab <- eq_loisir_hab %>% 
  mutate(Natation = Natation /population) %>%
  mutate(Boulodrome = Boulodrome/population) %>%
  mutate(Tennis = Tennis/population) %>% 
  mutate(eq_cyclisme = eq_cyclisme / population) %>% 
  mutate(athletisme = athletisme / population) %>% 
  mutate(terrain_golf = terrain_golf / population) %>% 
  mutate(parcours_sportif = parcours_sportif / population) %>%
  mutate(sports_de_glace = sports_de_glace / population) %>% 
  mutate(skate_park = skate_park / population) %>% 
  select(dep = code_insee, everything())
  
eq_loisir_hab

equip_loisir <- equip_loisir %>% 
  filter(!dep %in% c("971", "972", "973", "974"))

equip_loisir_tot <- equip_loisir %>%
  group_by(dep) %>%
  summarise(total = sum(nombre))

eq_loisir_hab <- merge(eq_loisir_hab, equip_loisir_tot, by ="dep")
eq_loisir_hab <- eq_loisir_hab %>% 
  mutate(total = total / population) %>% 
  select(-"population")
  
eq_loisir_hab <- eq_loisir_hab %>% 
  select(-loisir_total)

eq_loisir_hab <- eq_loisir_hab %>% 
  select(code_insee = dep, everything())
eq_loisir_hab <- merge(eq_loisir_hab, demographics_by_dep, by = "code_insee")

eq_loisir_hab <- eq_loisir_hab %>% 
  select(dep = code_insee, everything())

eq_loisir_hab <- merge(eq_loisir_hab, equip_loisir_tot, by = "dep")
eq_loisir_hab <- eq_loisir_hab %>% 
  mutate(total = total / population)

eq_loisir_hab <- eq_loisir_hab %>% 
  select(dep, total_loisir = total, everything())

eq_loisir_hab <- eq_loisir_hab %>% 
  select(-population)

eq_loisir_hab



```

```{r}
equipment <- merge(equipment, eq_loisir_hab, by = "dep")
names(equipment)
```

```{r}
names(equipment) <- c("dep", "Gendarmerie", "Cour_appel", "Tribunal_gd_instance", "Tribunal_instance", "Prudhommes", "Tribunal_commerce", "Bureau_poste", "Agence_postale_communale", "Taxi", "Aeroport", "Gare_TGV", "Gare_sans_TGV", "Sante_court_sejour", "Sante_moyen_sejour", "Sante_long_sejour", "Etablissement_psychiatrique", "Urgences", "Maternite", "Structure_psychiatrique_ambulatoire", "College", "Lycee_professionnel", "Lycee_general_techno", "Total_education", "Total_loisir", "Natation", "Boulodrome", "Tennis", "Cyclisme", "Athletisme", "Golf", "Parcours_sportif", "Sports_de_glace", "Skate_park")
```

```{r}

equipment

write.csv(equipment, "equipment_final.csv")

```


#Construction criminalité

```{r}

crime
```

```{r}
crime <- read.csv("Data/criminalite_dep.csv")

crime <- crime %>% 
  group_by(dpt) %>% 
  summarise(crime_rate = sum(nombre))

crime <- crime[c(1:96),]
crime

crime <- crime %>% 
  mutate(dpt = as.character(dpt)) %>% 
  mutate(dpt = case_when(
    nchar(dpt)==1 ~ paste0("0", dpt),
    TRUE ~ paste0("", dpt)
  ))

crime <- crime %>% 
  arrange(dpt) %>% 
  select(code_insee = dpt, crime_rate)


crime = merge(crime, demographics_by_dep, by = "code_insee")

crime <- crime %>% 
  mutate(crime_rate = crime_rate/population) %>% 
  select(dep = code_insee, crime_rate)

write.csv(crime, "crime_rate_dep.csv")


```



```{r}
#Fonction pour récupérer la moyenne et le chiffre pour un nom d'équipement et de département (donnée par le click)

get_info = function(eq, code_insee, data = data_dpt){
  eq <- enquo(eq)
  res <- data %>% 
    select(dep, equip = !!eq) %>% 
    mutate(equip = as.numeric(equip))
  med <- median(res%>% pull(equip))
  result <- res %>%
    filter(dep == code_insee) %>% 
    pull(equip)
  str <- paste0("Le ", code_insee, " a ",signif(result, 3), " ", eq, " par habitants, la médiane nationale étant de ", signif(med, 3))
  str2 <- glue::glue('Le {code_insee} a {signif(result, 3)} {eq} par habitants, la médiane nationale étant de {signif(med, 3)}')
  return(c(result, med))
}


indicateurs
get_info(eq = crime_rate, code_insee = 60, data = indicateurs)


# number <- get_info(niveau_vie, code_insee = 60)
# code_insee <- 60
# equip <- "Gendarmerie"
# 
# string <- glue::glue('Le {code_insee} a {signif(number[1], 3)} {equip} par habitant, la médiane nationale étant de {signif(number[2], 3)}')
# string

```















```{r}
equipment <- read.csv("Data/equipment_final.csv")
```


```{r}
names(equipment)

```

```{r}
names(equipment) <- c("X", "dep", "Gendarmerie", "Cour d'appel", "Tribunal de grande instance", "Tribunal d'instance", "Prudhommes", "Tribunal de commerce", "Bureau de poste", "Agence postale communale", "Taxi", "Aeroport", "Gare TGV", "Gare sans TGV", "Etablissement de sante court sejour", "Etablissement de sante moyen sejour", "Etablissement de sante long sejour", "Etablissement psychiatrique", "Urgences", "Maternite", "Structure psychiatrique ambulatoire", "College", "Lycee professionnel", "Lycee general ou technologique", "Education", "Equipements de loisirs", "Natation", "Boulodrome", "Tennis", "Cyclisme", "Athlestisme", "Golf", "Parcours sportif", "Sports de glace", "Skate park")

equipment

```

```{r}
data_dpt <- equipment

write.csv(equipment, "equipment_final.csv")
```



```{r}
names(indicateurs) <- c("dep", "taux de pauvrete", "niveau de vie", "taux de criminalite")
```

```{r}
indicateurs
write.csv(indicateurs, "indicateurs_final.csv")
```


```{r}
equipment <- read.csv("equipment_final.csv")
names(equipment)
equipment <- equipment[-1]
```

```{r}
equipment <- read.csv()


data_dpt
```

```{r}
equipment <- data_dpt
names(equipment)
```

```{r}
names(equipment) <- c("dep", "Gendarmerie", "Court of appeal", "High court", "District court", "Labor court", "Commercial court", "Post office", "communal postal agency", "Taxi", "Airport", "High-speed train station", "regular train station", "Short-stay health facility", "Medium-stay health facility", "Long-stay health facility", "Mental hospital", "Emergency room", "Maternity unit", "Psychiatric day hospital", "Middle-school", "Vocational school", "General and technology high-school", "Total education", "Total leisure", "Swimming resort", "Tennis", "Cycling", "Athleticism", "Golf course", "Fitness trail", "Ice-skating resort", "Skate park")
equipment
```

```{r}
write.csv(equipment, "equipment_en.csv")
```

```{r}
indicateurs
names(indicateurs)
```

```{r}
names(indicateurs)<- c("dep", "poverty rate", "median revenue", "crime rate")
write.csv(indicateurs, "indicateurs_en.csv")


data_indic <- read.csv("indicateurs_en.csv")
data_indic

data_eq <- read.csv("equipment_en.csv")
data_eq <- data_eq[-1]
data_eq
```

```{r}
names(data_eq) <- c("dep", "Gendarmerie", "Court of appeal", "High court", "District court", "Labor court", "Commercial court", "Post office", "communal postal agency", "Taxi", "Airport", "High-speed train station", "regular train station", "Short-stay health facility", "Medium-stay health facility", "Long-stay health facility", "Mental hospital", "Emergency room", "Maternity unit", "Psychiatric day hospital", "Middle-school", "Vocational school", "General and technology high-school", "Total education", "Total leisure", "Swimming resort", "French bowl pitch", "Tennis", "Cycling", "Athleticism", "Golf course", "Fitness trail", "Ice-skating resort", "Skate park")

write.csv(data_eq, "equipment_en.csv")

```


```{r}
indicateurs
```

```{r}
names(indicateurs) <- c("dep", "poverty rate", "median revenue", "crime rate")
indicateurs

write.csv(indicateurs, "Data/indicateurs_en.csv")
```

